#Repo Info
title: "Hello-World"
short-description: "The Hello World Template"
description: "This is your first repository"

category: "ONE Automation"
repor-url: "https://github.com/Automic-Community/Hello-World" 


#Submiter Info

first-name: "Ben"
last-name: "Smith"
email: "ben@automic.com"

twitter_username: "@benben"
github_username:  "benSmith"


